HarvestHub/Controllers/InsumoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HarvestHub.Data;
using HarvestHub.Models;
using HarvestHub.ViewModels;

namespace HarvestHub.Controllers
{
    public class InsumoController : Controller
    {
        private readonly HarvestHubContext _context;

        public InsumoController(HarvestHubContext context)
        {
            _context = context;
        }
        
        // GET: Insumo
        public async Task<IActionResult> Index()
        {
            var insumos = await _context.Insumos
                .Include(insumo => insumo.GerenteDeProducao)
                .ToListAsync();
            
            
            return View(insumos.ConvertAll(insumo => new IndexInsumoViewModel
            {
                Tipo = insumo.TipoInsumo,
                Codigo = insumo.CodInsumo,
                Descricao = insumo.Descricao,
                Crea = insumo.GerenteDeProducao.CREA,
                Custo = insumo.Custo,
                Id = insumo.IdInsumo,
                Marca = insumo.Marca,
                Volume = insumo.Volume
            }));
        }
        
        // GET: Insumo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Insumo/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Tipo,Codigo,Volume,Custo,Descricao,Marca,Crea")] CreateInsumoViewModel viewmodel)
        {
            foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
            {
                Console.WriteLine(error.ErrorMessage);
            }
            
            if (ModelState.IsValid)
            {
                var gerente = await _context.GerenteDeProducao
                    .Include(gerente => gerente.Funcionario)
                    .Include(gerente => gerente.Insumos)
                    .FirstOrDefaultAsync(gerente => gerente.CREA == viewmodel.Crea);
                
                if (gerente == null)
                {
                    viewmodel.Crea = "";
                    return View(viewmodel);
                }
                
                var insumo = new Insumo
                {
                    TipoInsumo = viewmodel.Tipo,
                    CodInsumo = viewmodel.Codigo,
                    Volume = viewmodel.Volume,
                    Custo = viewmodel.Custo,
                    Descricao = viewmodel.Descricao,
                    Marca = viewmodel.Marca,
                    GerenteDeProducaoId = gerente.Funcionario.Id,
                    GerenteDeProducao = gerente,
                    Estoques = new List<Estoque>()
                };
                
                _context.Insumos.Add(insumo);
                gerente.Insumos.Add(insumo);
                
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewmodel);
        }
        

        // GET: Insumo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var insumo = await _context.Insumos
                .Include(insumo => insumo.GerenteDeProducao)
                .FirstOrDefaultAsync(m => m.IdInsumo == id);
            
            if (insumo == null)
            {
                return NotFound();
            }

            var viewmodel = new DeleteInsumoViewModel
            {
                Tipo = insumo.TipoInsumo,
                Codigo = insumo.CodInsumo,
                Volume = insumo.Volume,
                Custo = insumo.Custo,
                Descricao = insumo.Descricao,
                Marca = insumo.Marca,
                Crea = insumo.GerenteDeProducao.CREA
            };

            return View(viewmodel);
        }

        // POST: Insumo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var insumo = await _context.Insumos.FindAsync(id);
            if (insumo != null)
            {
                _context.Insumos.Remove(insumo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
    }
}

HarvestHub/Controllers/ProducaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HarvestHub.Data;
using HarvestHub.Models;

namespace HarvestHub.Controllers
{
    public class ProducaoController : Controller
    {
        private readonly HarvestHubContext _context;

        public ProducaoController(HarvestHubContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Producoes.ToListAsync());
        }
        // GET: Producao/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Producao/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdProducao,Tipo,Custo,Volume")] Producao producao)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producao);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(producao);
        }

    }
}

HarvestHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HarvestHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HarvestHub.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HarvestHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producao" asp-action="Index">Production</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Insumo" asp-action="Index">Insumo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patrimonios" asp-action="Index">Patrimônios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fornecedores" asp-action="Index">Fornecedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GerenteDeProducao" asp-action="Index">Gerente de Producao</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RecursosHumanos" asp-action="Index">Recursos Humanos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contador" asp-action="Index">Contador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GerenciarBalanco" asp-action="Index">Gerenciar Balanço</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - HarvestHub
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>